### ISSUE TITLE
Spostamento repo, inserita variabile 'incarico'. Tentativo di inserire data di nascita

### ISSUE THREAD

**Issue by EricaRavarelli** [DataAccess2020/Capstone_project#1]
@DeAngelisA repo spostata, scusi il disguido
Ora sto pulendo e ricodificando i dati, ho deciso di inserire la variabile "incarico" per avere un'idea del background professionale del/della deputato/a, come mi aveva suggerito (l'età non c'era).

**Comment by Nico-Casarin** [comment]
@EricaRavarelli  in teoria la data di nascita c'è!
```
?persona <http://purl.org/vocab/bio/0.1/Birth> ?nascita .
?nascita <http://purl.org/vocab/bio/0.1/date> ?dataNascita .
```
Se hai bisogno possiamo darci una mano :construction_worker:

edit:
persona come:
`?persona ocd:rif_mandatoCamera ?mandato; a foaf:Person .`

**Comment by EricaRavarelli** [comment]
Hai ragione @n-oise, grazie! Ora provo a inserirla

**Comment by Nico-Casarin** [comment]
Sono riuscito ad ottenere un risultato del genere:

```json
{
    "head": {
        "link": [],
        "vars": [
            "cognome",
            "nome",
            "genere",
            "dataNascita"
        ]
    }
}
```

**Comment by DeAngelisA** [comment]
@n-oise : ottimo, aiutatevi pure può uscire un bel dataset. Toglierei però dati sui parlamentari da questa repo pubblica!

**Comment by Nico-Casarin** [comment]
@DeAngelisA: capisco la sua preoccupazione, modifico i dati. Li ho pubblicati (nonché caricati anche sulla mia repo) esclusivamente in quanto sono distribuiti come parte del progetto Linked Open Data e sono liberamente sharable!

**Comment by EricaRavarelli** [comment]
Avevo fatto lo stesso ragionamento di @n-oise sulla pubblicazione dei dati, ma se preferisce modifico

**Comment by DeAngelisA** [comment]
Se avete il permesso va bene cosí.

**Comment by EricaRavarelli** [comment]
@n-oise Ho provato a inserire questo codice dando un'occhiata agli esempi. Mi sembra che l'unica cosa che cambia rispetto a quello che mi avevi suggerito tu è la variabile ?d che starebbe per deputato, però non capisco perché sia necessario inserirla visto che nella mia query è già specificata...

?persona ocd:rif_mandatoCamera ?mandato; a foaf:Person.

 deputato
?d a ocd:deputato;
ocd:rif_leg <http://dati.camera.it/ocd/legislatura.rdf/repubblica_17>;
ocd:rif_mandatoCamera ?mandato.


 anagrafica
?d foaf:surname ?cognome; foaf:gender ?genere;foaf:firstName ?nome.
?persona <http://purl.org/vocab/bio/0.1/Birth> ?nascita.
?nascita <http://purl.org/vocab/bio/0.1/date> ?dataNascita.

**Comment by Nico-Casarin** [comment]
Per ottenere il risultato che ti ho linkato sopra ho usato questa query: 
```SPARQL
SELECT ?persona ?mandato ?cognome ?nome ?genere ?dataNascita 
WHERE {
 
?persona ocd:rif_mandatoCamera ?mandato;
           a foaf:Person. 
  
?mandato ocd:rif_leg <http://dati.camera.it/ocd/legislatura.rdf/repubblica_18> . 

?persona foaf:surname ?cognome; foaf:gender ?genere;foaf:firstName ?nome.

?persona <http://purl.org/vocab/bio/0.1/Birth> ?nascita.
?nascita <http://purl.org/vocab/bio/0.1/date> ?dataNascita. 

 }
GROUP BY ?persona
LIMIT 10
````

Quindi molto molto simile. Se non ti serve la `?d` non usarla. Sono variabili "transitive"

**Comment by DeAngelisA** [comment]
Fantastico @n-oise. Magari puoi dare a Erica anche un po' di contesto o un tutorial/risorsa online su come construire queste query? Ottimo lavoro.

**Comment by Nico-Casarin** [comment]
@DeAngelisA @EricaRavarelli,  sfortunatamente la documentazione specifica è molto carente. Come aiuto per la costruzione delle query può esser la [wiki di Virtuoso](http://vos.openlinksw.com/owiki/wiki/VOS/) e gli [use cases](http://dati.camera.it/ocd/use_cases/) della camera.... anche se questi ultimi non sono sempre corretti. 
Inoltre è essenziale la consultazione dell'[ontologia della Camera dei Deputati](http://dati.camera.it/ocd/reference_document/) per capire come costruire le triple `soggetto-predicato-oggetto`!
