### ISSUE TITLE
più di 10000 osservazioni

### ISSUE THREAD

**Issue by EricaRavarelli** [DataAccess2020/Capstone_project#2]
@n-oise avrei bisogno di una mano con la query perché devo prendere tutti gli interventi che sono stati fatti da deputati e deputate durante la XVII legislatura ma non riesco a capire come importare più di 10 000 osservazioni. Da quello che ho visto tu ci sei riuscito, mi puoi dire che passaggi hai seguito? Io ho provato a seguire i passaggi che hai fatto ma penso di avere dei problemi a capire come funziona la subquery

**Comment by Nico-Casarin** [comment]
Devi lavorare con le subquery, come già hai evidenziato te! [Qui](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed) puoi trovare una spiegazione abbastanza chiara su come implementarla. Se hai qualche problema specifico dimmi pure.
Come per gli altri problemi mi sento di consigliarti di lavorare prima su piccoli numeri per capire come funziona l'OFFSET! 
Let me know :grin:
