### ISSUE TITLE
Take only speeches in governo Renzi

### ISSUE THREAD

**Issue by EricaRavarelli** [DataAccess2020/Capstone_project#3]
@n-oise sono riuscita a prendere più di 10 000 osservazioni, solo che sto pensando di concentrarmi su un governo piuttosto che su tutta la legislatura, altrimenti avrei più di 200 mila osservazioni. Ho provato in vari modi, quello che credo abbia più senso è inserire nella query `?dibattito ocd:rif_leg <http://dati.camera.it/ocd/legislatura.rdf/repubblica_17>; ocd:rif_governo <http://dati.camera.it/ocd/governo.rdf/g102>.` , per prendere solo gli interventi di deputati e deputate durante il governo Renzi. Ho provato anche a definire prima la variabile legislatura e solo in seguito la variabile governo, un po' come avevo fatto per persona e data di nascita, ma non riesco comunque. Tu hai idea di come potrei risolvere?

**Comment by Nico-Casarin** [comment]
mmm! si può fare, ma non mi ricordo come sono collegate le triple. A memoria mi pare che il dibattito abbia già il rif al governo come ontologia

**Comment by EricaRavarelli** [comment]
[http://dati.camera.it/ocd/dibattito.rdf/dib137691_18](dibattito) ti linko un dibattito a caso, da quello che ho capito mi sembra che il riferimento al governo non ci sia, bisogna passare per la legislatura

**Comment by Nico-Casarin** [comment]
Mi sa che la ocd:dibattito non ha il rif_gov.. allora potresti "imbrogliare" e filtrare tramite data?
Qualcosa tipo filter: `dibattito.startDate > governo.startDate ` and `dibattito.endDate < governo.endDate`.

p.s. mi sa che nel fare il link al dibattito hai invertito la label con l'url. Praticamente "http://dati.camera.it/ocd/dibattito.rdf/dib137691_18" rimanda ad una pagina "dibattito" 😁 


Edit: oppure ti scarichi one shot tutti quelli di una legislatura, li lavori e poi filtri quelli che non ti interessano. Tenendo però al sicuro tutti gli altri così se cambi idea sono sempre li. Alla fine salvandoli come .csv occupano davvero davvero poco spazio!

**Comment by EricaRavarelli** [comment]
Si avevo pensato a filtrare ma mi era venuto in mente solo con le regex e non sarebbe venuto preciso, ora provo come mi hai suggerito tu, grazie!
Si scusa ahah ti ho risposto dal cellulare e ho fatto un mezzo casino😄

**Comment by Nico-Casarin** [comment]
Capito! Se vuoi con il pacchetto lubridate potresti usare la funzione interval() molto comoda per lavorare con start-end dates.
